'use strict';

const nodemailer = require('nodemailer');

function createTransporter() {
  return nodemailer.createTransport({
    host:   process.env.SMTP_HOST,
    port:   parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

// ── Plain-text report ────────────────────────────────────────

function buildPlainText(report, transcript) {
  const tasks = report.tasksCompleted?.length
    ? report.tasksCompleted.map((t) => `  • ${t}`).join('\n')
    : '  None reported';

  const incidents = report.incidentsOrIssues?.length
    ? report.incidentsOrIssues.map((i) => `  ⚠ ${i}`).join('\n')
    : '  None';

  const s = report.staffSummary ?? {};
  const staffLines = [
    s.totalHoursAllStaff         ? `  Total Hours (All Staff):        ${s.totalHoursAllStaff}` : null,
    s.totalHoursIndigenousStaff  ? `  Total Hours (Indigenous Staff): ${s.totalHoursIndigenousStaff}` : null,
    s.maleStaffCount   != null   ? `  Male Staff Count:               ${s.maleStaffCount}` : null,
    s.femaleStaffCount != null   ? `  Female Staff Count:             ${s.femaleStaffCount}` : null,
    s.otherNotes                 ? `  Notes: ${s.otherNotes}` : null,
  ].filter(Boolean);

  return [
    'LORETRACK FIELD REPORT',
    '══════════════════════════════════════════',
    `Worker:       ${report.workerName || 'Unknown'}`,
    `Date:         ${report.date || 'Unknown'}`,
    `Hours Worked: ${report.hoursWorked || 'Not specified'}`,
    '',
    'TASKS COMPLETED',
    tasks,
    '',
    'INCIDENTS / ISSUES',
    incidents,
    ...(staffLines.length ? ['', 'STAFF SUMMARY', ...staffLines] : []),
    ...(report.additionalNotes ? ['', 'ADDITIONAL NOTES', `  ${report.additionalNotes}`] : []),
    '',
    '──────────────────────────────────────────',
    'ORIGINAL TRANSCRIPT',
    transcript,
    '══════════════════════════════════════════',
    'Generated by LoreTrack',
  ].join('\n');
}

// ── HTML report ──────────────────────────────────────────────

function buildHtml(report, transcript) {
  const taskItems = report.tasksCompleted?.length
    ? report.tasksCompleted.map((t) => `<li>${esc(t)}</li>`).join('')
    : '<li><em>None reported</em></li>';

  const incidentItems = report.incidentsOrIssues?.length
    ? report.incidentsOrIssues
        .map((i) => `<li style="color:#922B21">⚠ ${esc(i)}</li>`)
        .join('')
    : '<li><em>None</em></li>';

  const s = report.staffSummary ?? {};
  const staffRows = [
    s.totalHoursAllStaff        ? row('Total Hours (All Staff)',        s.totalHoursAllStaff) : '',
    s.totalHoursIndigenousStaff ? row('Total Hours (Indigenous Staff)', s.totalHoursIndigenousStaff) : '',
    s.maleStaffCount   != null  ? row('Male Staff Count',               s.maleStaffCount) : '',
    s.femaleStaffCount != null  ? row('Female Staff Count',             s.femaleStaffCount) : '',
    s.otherNotes                ? row('Notes',                          s.otherNotes) : '',
  ].join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1A1A1A;background:#F5F0E8}
  .card{background:#fff;border-radius:12px;padding:24px;margin-bottom:16px;border:1px solid #DDD5C4}
  h1{background:#1B3A4B;color:#fff;padding:16px 22px;border-radius:10px;font-size:20px;margin:0 0 16px}
  h2{font-size:13px;text-transform:uppercase;letter-spacing:.8px;color:#6B6B6B;margin:0 0 10px}
  dl{display:grid;grid-template-columns:1fr 1fr;gap:4px 12px}
  dt{font-size:13px;color:#6B6B6B}
  dd{font-size:15px;font-weight:600}
  ul{padding-left:20px;margin:0}
  li{margin:4px 0;font-size:15px}
  table{width:100%;border-collapse:collapse}
  td{padding:8px 0;border-bottom:1px solid #EEE;font-size:14px}
  td:first-child{color:#6B6B6B;width:55%}
  .transcript{background:#F9F9F9;border-left:4px solid #1B3A4B;padding:14px;font-style:italic;font-size:14px;border-radius:0 8px 8px 0}
  .footer{text-align:center;font-size:12px;color:#999;margin-top:20px}
</style>
</head>
<body>
<h1>🌿 LoreTrack Field Report</h1>

<div class="card">
  <h2>Worker Details</h2>
  <dl>
    <dt>Name</dt><dd>${esc(report.workerName || '—')}</dd>
    <dt>Date</dt><dd>${esc(report.date || '—')}</dd>
    <dt>Hours Worked</dt><dd>${esc(report.hoursWorked || '—')}</dd>
  </dl>
</div>

<div class="card">
  <h2>Tasks Completed</h2>
  <ul>${taskItems}</ul>
</div>

<div class="card">
  <h2>Incidents / Issues</h2>
  <ul>${incidentItems}</ul>
</div>

${staffRows ? `<div class="card"><h2>Staff Summary</h2><table>${staffRows}</table></div>` : ''}

${report.additionalNotes ? `<div class="card"><h2>Additional Notes</h2><p style="font-size:15px">${esc(report.additionalNotes)}</p></div>` : ''}

<div class="card">
  <h2>Original Transcript</h2>
  <div class="transcript">${esc(transcript)}</div>
</div>

<div class="footer">Generated by LoreTrack — Voice Field Reporting</div>
</body>
</html>`;
}

function row(label, value) {
  return `<tr><td>${esc(label)}</td><td><strong>${esc(String(value))}</strong></td></tr>`;
}

function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ── Public API ───────────────────────────────────────────────

/**
 * Send the structured report to the supervisor's email.
 *
 * @param {Object} report          - Structured report from Claude
 * @param {string} supervisorEmail
 * @param {string} transcript      - Original Whisper transcript
 */
async function sendReport(report, supervisorEmail, transcript) {
  const transporter = createTransporter();
  const from = process.env.SMTP_FROM || process.env.SMTP_USER;
  const workerName = report.workerName || 'Field Worker';
  const date = report.date || new Date().toLocaleDateString('en-AU');

  await transporter.sendMail({
    from,
    to: supervisorEmail,
    subject: `LoreTrack Report: ${workerName} – ${date}`,
    text: buildPlainText(report, transcript),
    html: buildHtml(report, transcript),
  });
}

module.exports = { sendReport };
